// Define the translation structure as a const assertion first
export const en = {
  home: {
    getStarted: "Get started by editing",
    saveAndSee: "Save and see your changes instantly.",
    deployNow: "Deploy now",
    readDocs: "Read our docs"
  },
  footer: {
    learn: "Learn",
    examples: "Examples",
    goToNextjs: "Go to nextjs.org →",
    language: "Language"
  },
  layout: {
    title: "Create Next App",
    description: "Generated by create next app"
  }
} as const; 