export const en = {
  "home.getStarted": "Get started by editing",
  "home.saveAndSee": "Save and see your changes instantly.",
  "home.deployNow": "Deploy now",
  "home.readDocs": "Read our docs",
  "footer.learn": "Learn",
  "footer.examples": "Examples",
  "footer.goToNextjs": "Go to nextjs.org →",
  "footer.language": "Language",
  "layout.title": "Create Next App",
  "layout.description": "Generated by create next app"
} as const; 